# Generated by Django 4.2.4 on 2023-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_membership_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='rship',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Single'), ('2', 'In a relationship'), ('3', 'Married'), ('4', 'Engaged')], default='None', max_length=1),
        ),
    ]
