# Generated by Django 4.2.4 on 2023-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_rship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rship',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Single'), ('2', 'In a relationship'), ('3', 'Married'), ('4', 'Engaged')], default='None', max_length=1),
        ),
    ]
