# Generated by Django 4.2.4 on 2023-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_rship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rship',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
