# Generated by Django 4.2.4 on 2023-08-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_rship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rship',
        ),
    ]
