# Generated by Django 4.2.4 on 2023-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_rship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
