# Generated by Django 4.2.4 on 2023-08-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profile_rship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rship',
        ),
    ]
