# Generated by Django 4.2.4 on 2023-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
