# Generated by Django 4.2.4 on 2023-08-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='stats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
