# Generated by Django 4.2.4 on 2023-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_followercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_disliked',
            field=models.IntegerField(default=0),
        ),
    ]
