# Generated by Django 4.2.4 on 2023-08-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_post_no_of_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_dislikes',
        ),
    ]
