# Generated by Django 4.2.4 on 2023-08-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_post_no_of_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_disliked',
            new_name='no_of_dislikes',
        ),
    ]
