# Generated by Django 4.2.4 on 2023-08-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_no_of_disliked_post_no_of_dislikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCount',
            new_name='Follower',
        ),
    ]
