# Generated by Django 4.2.4 on 2023-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_followercount_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=100)),
                ('commenter', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
