# Generated by Django 4.2.4 on 2023-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
